# Generated by Django 4.0.5 on 2022-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_filme_classificacao_alter_filme_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(max_length=2, verbose_name='classificação'),
        ),
    ]
